apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod-score-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-scheduling
  template:
    metadata:
      labels:
        app: test-scheduling
    spec:
      nodeName: node2          # 指定主机节点
      serviceAccount: test-scheduling-sa # 绑定的serviceAccount
      containers:
        - name: tests-scheduling
          image: crpi-wpd2fghu4joh4sz7.cn-beijing.personal.cr.aliyuncs.com/cszdm/test-score-scheduler-plugins:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: "Release"
              value: "1"
          command: ["./test-pod-score-scheduler"]
          args:
            - --config=/etc/kubernetes/config.yaml
            - --v=3
          volumeMounts:
            - name: config # 挂载目录
              mountPath: /etc/kubernetes
      volumes:
        - name: config # 挂载对象
          configMap:
            name: test-scheduling-config